schema_version = "1.0.0"
id = "CyberCatppuccin"
name = "Cyber Catppuccin"
version = "1.0.0"
tagline = "A sleek Cyberpunk-infused Catppuccin Mocha theme for Blender"
maintainer = "Demigirlboss"
type = "theme"
tags = ["Dark", "Catppuccin", "Cyberpunk", "Mocha"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
